yahboomcar:
  # Joint State Controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Individual Joint Position Controllers for Arm
  arm_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint1
    pid: {p: 1000.0, i: 0.0, d: 0.1}

  arm_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint2
    pid: {p: 1000.0, i: 0.0, d: 0.1}

  arm_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint3
    pid: {p: 1000.0, i: 0.0, d: 0.1}

  arm_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint4
    pid: {p: 1000.0, i: 0.0, d: 0.1}

  arm_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint5
    pid: {p: 1000.0, i: 0.0, d: 0.1}

  # Gripper Position Controller
  gripper_position_controller:
    type: effort_controllers/JointPositionController
    joint: grip_joint
    pid: {p: 1000.0, i: 0.0, d: 0.1}